branches: 
  - main

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/github'
    - assets:
      - path: 'build/snail-release'
        label: snail-release
