name: Release

on: workflow_dispatch

env:
  DENO_DIR: .cache

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('lock.json') }}

      - name: Build binaries
        run: |
          deno task build:linux
          deno task build:win
          deno task build:macos
          deno task build:macos-arm
      
      - name: Compute checksums
        run: |
          sha256sum dist/snail-release-linux-x86_64 >> checksums.md
          sha256sum dist/snail-release-win-x86_64 >> checksums.md
          sha256sum dist/snail-release-darwin-x86_64 >> checksums.md
          sha256sum dist/snail-release-darwin-arm64 >> checksums.md

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: snail-release
          path: |
            dist/
            checksums.md
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: snail-release
          path: |
            dist/
            checksums.md

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}